Feature/protected routes #28
hatchways/team-chicken-noodle pull request #47
Opened 2021-10-01 13:58 UTC by parasVohra

### What this PR does (required):
- Created the protected route component which performs an authentication check before accessing the component.
- If the user is not authenticated then he will be redirected to the login page.

### Screenshots / Videos (required):

https://user-images.githubusercontent.com/19547204/135632418-67977069-9470-4862-8385-64ff829d0251.mov

### Any information needed to test this feature (required):
- Try to access the dashboard component without singing by typing /dashboard in the URL.

2021-10-01 15:07 UTC, ezeilo-su reviewed
Good work implementing this one. Please always remember to link the issue in your PR.
Happy coding!

2021-10-01 15:07 UTC, ezeilo-su commented on client/src/components/ProtectedRoutes/ProtectedRoutes.tsx
> +  if (auth.loggedInUser === null || auth.loggedInUser === undefined) return <Redirect to="/login" />;
This test can be written like this: `if (!auth.loggedInUser)` since both `null` and `undefined` are Falsy.

2021-10-04 09:58 UTC, ugur-akin commented on client/src/components/ProtectedRoutes/ProtectedRoutes.tsx
> +const ProtectedRoutes: React.FC<RouteProps> = ({ ...rest }) => {
```suggestion
const ProtectedRoute: React.FC<RouteProps> = ({ ...rest }) => {
```

2021-10-04 09:59 UTC, ugur-akin approved these changes
LGTM! I left a minor name change suggestion that will improve code clarity, please address before merging.

2021-10-04 16:21 UTC, moffatethan requested changes
Another PR has code related to Protected Route, please fix PR #43 before merging this

2021-10-05 17:03 UTC, moffatethan approved these changes
LGTM!

2021-10-05 17:12 UTC, merged